### ISSUE TITLE
Docs button offscreen when screen is too small

### ISSUE THREAD

**Issue by jc00ke** [OlegIlyenko/graphql-toolbox#10]
On some laptops you can't get to the documentation. Here's a screenshot showing the issue:

![ping-no-docs](https://cloud.githubusercontent.com/assets/18191/21629284/cacaa5ca-d1db-11e6-90f4-15e4ae11c81c.png)

I poked around for a bit but my CSS chops aren't really chops anymore.

**Comment by OlegIlyenko** [comment]
This issued was fixed a while back: https://github.com/OlegIlyenko/graphql-toolbox/commit/3c0980e17124e86ed13b0c54ea6ab8005d40b53f

Maybe you are using an outdated version?

**Comment by jc00ke** [comment]
Looks like we're using `1.0.1` from http://www.jsdelivr.com/projects/graphql-toolbox via [Absinthe Plug](https://github.com/absinthe-graphql/absinthe_plug/blob/a0b1a500feb7fd006538faca306e9c0a834be54d/lib/absinthe/plug/graphiql.ex#L19) /c @bruce

**Comment by decebal** [comment]
Not sure how you're running this repo but the fix is not part of your master and I really wanted to extend this fix to some more components like the `recent history tab` and `the query tab` in it's collapsed state that have the same issue, could you help me out a little, please ?

**Comment by decebal** [comment]
nvm, so it's all moved into [workspace](https://github.com/OlegIlyenko/graphiql-workspace) now, :+1:

**Comment by decebal** [comment]
`collapsed state` and `recent tokens` have the same problem referenced by @OlegIlyenko as being fixed. Also it looks like the cdn version [latest](http://cdn.jsdelivr.net/graphql-toolbox/latest/graphiql.min.js) it's not updated either :(

**Comment by OlegIlyenko** [comment]
@decebal I would suggest you to check "Standalone Usage" of the graphiql-workspace docs: 

https://github.com/OlegIlyenko/graphiql-workspace#standalone-usage

**Comment by jc00ke** [comment]
OK, so looks like this was fixed in https://github.com/OlegIlyenko/graphiql-workspace/commit/587ae65d365a7aec59c1d19df850181e5ba4abb8 which is what Absinthe.Plug uses.
