### ISSUE TITLE
Schema-stitching

### ISSUE THREAD

**Issue by inakianduaga** [OlegIlyenko/graphql-toolbox#14]
Not sure whether this would belong here or in the main Sangria repo, but the question is if there are plans to bring [schema-stitching](https://www.apollographql.com/docs/graphql-tools/schema-stitching.html) functionality? Would really help integrating different backends as they move from REST to GraphQL

**Comment by OlegIlyenko** [comment]
Schema stitching is definitely very interesting area. I made several experiments with it as well. For example here is an example of how one might get started with the implementation:

https://github.com/OlegIlyenko/graphql-toolbox/blob/master/app/controllers/Materializer.scala

Although the topic in itself is quite big. I think it can be a big project on its own. Several community members are already working on fully functional implementation of it (e.g. Graphcool, Apollo and APIs.Guru).

On the other hand, for me (and also in the scope of graphql-toolbox) it was important to verify that something like this is possible to implement with sangria and if not, then to identify the bottlenecks and missing functionality. So far it looks pretty good but at the moment it is outside of the scope to implement fully features GraphQL API gateway (just the matter of time and effort needed to implement this thing)

**Comment by inakianduaga** [comment]
> Several community members are already working on fully functional implementation of it (e.g. Graphcool, Apollo and APIs.Guru).

@OlegIlyenko Do you know of any progress? I can't find anything online

**Comment by Codier** [comment]
@OlegIlyenko would love to know if there is any progress.

**Comment by OlegIlyenko** [comment]
@Codier In fact the is a bit of progress in this direction. It is still at early stages, but I extracted relevant parts in a separate project and made this functionality standalone:

https://github.com/OlegIlyenko/graphql-gateway

moreover, it is much easier to use use this functionality. You can just run it with docker like this:

```bash
docker run -it -p 8080:8080 -v $(pwd):/schema tenshi/graphql-gateway
```

and it will serve the schema defined in `*.graphql` files in the current working  directory (it will also pick up and reload all changes to these files).

You can check out this example schema: [testSchema.graphql](https://github.com/OlegIlyenko/graphql-gateway/blob/master/testSchema.graphql)

I would suggest you to check it out and would appreciate your feedback if you decide to try it out.
