### ISSUE TITLE
Proxy demo doesn't work

### ISSUE THREAD

**Issue by krabbypattified** [OlegIlyenko/graphql-toolbox#15]
http://toolbox.sangria-graphql.org/proxy

**Comment by OlegIlyenko** [comment]
Just checked it and it works as expected. Maybe you can describe the issue in more detail? (also it is deployed to a free heroku node, so sometimes it goes to sleep and takes some time to wake up)

**Comment by krabbypattified** [comment]
It appears the default query throws a validation error.
Is that intended?

```
query {
  person(id: 1) {
    name
    size

    homeworld {
      name
    }

    films {
      title
    }
  }

  films {
    title
  }
}
```

![screen shot 2017-11-24 at 4 46 01 pm](https://user-images.githubusercontent.com/13423815/33224421-4a92f9e6-d137-11e7-97ee-e4c77b8d44d9.png)

**Comment by OlegIlyenko** [comment]
Fixed: https://github.com/OlegIlyenko/graphql-toolbox/commit/94449da19d03c04ddf2978a40c0edb6d9527bc9a
