### ISSUE TITLE
Abbreviate headers

### ISSUE THREAD

**Issue by bali182** [OlegIlyenko/graphql-toolbox#8]
This is graphiql related, hope it's still the right repo for it.

When you have a very long header, it pushes out the controls next to it, making them hard to reach (you can't actually I had to inspect the source and delete the labels contents):

![bug-headers](https://cloud.githubusercontent.com/assets/3879181/20457835/fb4ee17a-ae8b-11e6-8600-a3309824ed79.png)

I think it would be nice to abbreviate the headers text to a reasonable size (like 50 chars or so) to avoid this problem

**Comment by OlegIlyenko** [comment]
I fixed it a while ago: https://github.com/OlegIlyenko/graphql-toolbox/commit/3c0980e17124e86ed13b0c54ea6ab8005d40b53f

Maybe you are using outdated version?

**Comment by tlvenn** [comment]
We most likely need to publish a new version to jsdelivr that includes this fix but for that we need to publish graphql-toolbox as a npm package first for jsdelivr to pick up the update automatically.

**Comment by tlvenn** [comment]
And just in case, this could be of help for publishing to npm: https://github.com/sindresorhus/np

**Comment by bali182** [comment]
Yep, I'm using the (most likely outdated jsdelivr version). Closing this issue since the problem doesn't exist in the current codebase. Out of curiosity, are there any plans to release this as an npm package?
